//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Untangle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AboutBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Untangle.Resources.AboutBox", typeof(AboutBox).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        internal static string btn_Close_Content {
            get {
                return ResourceManager.GetString("btn_Close_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External libraries used were created by Uwe Mayer, Konrad Mattheis, and Bernhard Millauer, and licensed under Microsoft Public License, available at [a href=&apos;http://opensource.org/licenses/MS-PL&apos;]http://opensource.org/licenses/MS-PL[/a]..
        /// </summary>
        internal static string tb_3rdPartyLicenses_Text {
            get {
                return ResourceManager.GetString("tb_3rdPartyLicenses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Aleksandar Dalemski ([a href=&apos;mailto:a_dalemski@yahoo.com&apos;]a_dalemski@yahoo.com[/a]).
        /// </summary>
        internal static string tb_Author_Text {
            get {
                return ResourceManager.GetString("tb_Author_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under Mozilla Public License, version 2.0, available at [a href=&apos;http://www.mozilla.org/MPL/2.0/&apos;]http://www.mozilla.org/MPL/2.0/[/a]..
        /// </summary>
        internal static string tb_License_Text {
            get {
                return ResourceManager.GetString("tb_License_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code is available at [a href=&apos;https://sourceforge.net/projects/untanglegame/&apos;]https://sourceforge.net/projects/untanglegame/[/a]..
        /// </summary>
        internal static string tb_SourceCode_Text {
            get {
                return ResourceManager.GetString("tb_SourceCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untangle.
        /// </summary>
        internal static string tb_Title_Text {
            get {
                return ResourceManager.GetString("tb_Title_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tb_Translator_Text {
            get {
                return ResourceManager.GetString("tb_Translator_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string tb_VersionCaption_Text {
            get {
                return ResourceManager.GetString("tb_VersionCaption_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Game.
        /// </summary>
        internal static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
