//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Untangle.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Untangle.Resources.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        internal static string mi_About_Header {
            get {
                return ResourceManager.GetString("mi_About_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        internal static string mi_Edit_Header {
            get {
                return ResourceManager.GetString("mi_Edit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        internal static string mi_Exit_Header {
            get {
                return ResourceManager.GetString("mi_Exit_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        internal static string mi_File_Header {
            get {
                return ResourceManager.GetString("mi_File_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string mi_Help_Header {
            get {
                return ResourceManager.GetString("mi_Help_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        internal static string mi_Language_Header {
            get {
                return ResourceManager.GetString("mi_Language_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level _Builder.
        /// </summary>
        internal static string mi_LevelBuilder_Header {
            get {
                return ResourceManager.GetString("mi_LevelBuilder_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Load game....
        /// </summary>
        internal static string mi_LoadGame_Header {
            get {
                return ResourceManager.GetString("mi_LoadGame_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New game.
        /// </summary>
        internal static string mi_NewGame_Header {
            get {
                return ResourceManager.GetString("mi_NewGame_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        internal static string mi_Redo_Header {
            get {
                return ResourceManager.GetString("mi_Redo_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save game....
        /// </summary>
        internal static string mi_SaveGame_Header {
            get {
                return ResourceManager.GetString("mi_SaveGame_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se_ttings.
        /// </summary>
        internal static string mi_Settings_Header {
            get {
                return ResourceManager.GetString("mi_Settings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        internal static string mi_Undo_Header {
            get {
                return ResourceManager.GetString("mi_Undo_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersections:.
        /// </summary>
        internal static string tb_Intersections_Text {
            get {
                return ResourceManager.GetString("tb_Intersections_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves:.
        /// </summary>
        internal static string tb_Moves {
            get {
                return ResourceManager.GetString("tb_Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertices:.
        /// </summary>
        internal static string tb_Vertices_Text {
            get {
                return ResourceManager.GetString("tb_Vertices_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untangle - Level {0}.
        /// </summary>
        internal static string WindowTitleFormat {
            get {
                return ResourceManager.GetString("WindowTitleFormat", resourceCulture);
            }
        }
    }
}
